package com.smartshop.user.entity;

import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;

/**
 * User - JPA Entity Representing a SmartShop Platform User
 *
 * <h2>Purpose</h2>
 * The central domain object for the user service. Maps to the "users" table in
 * PostgreSQL. Contains all user profile information plus authentication credentials
 * (hashed password) and role assignment.
 *
 * <h2>Key Concepts</h2>
 * <ul>
 *   <li>@Entity: Marks this class as a JPA entity — Hibernate will manage its
 *       lifecycle (persistence, updates, queries). Every @Entity must have an @Id field.</li>
 *   <li>@EntityListeners(AuditingEntityListener.class): Connects Spring's auditing
 *       infrastructure to this entity. Enables automatic population of @CreatedDate,
 *       @LastModifiedDate, @CreatedBy, @LastModifiedBy before each save/update.</li>
 *   <li>Why DTOs instead of Entities? We NEVER return this entity directly from
 *       controllers. Reasons:
 *       1. The passwordHash field would be exposed in API responses (security risk!)
 *       2. Entities can have lazy-loaded associations that cause N+1 queries
 *       3. The entity shape might change; DTOs provide a stable API contract
 *       4. Entities are managed by Hibernate — controllers shouldn't hold references</li>
 *   <li>@Column(unique = true): Creates a UNIQUE constraint in the database.
 *       Two users cannot have the same email. The constraint is enforced at the DB
 *       level, not just application level (prevents race conditions in concurrent registrations).</li>
 *   <li>@Enumerated(EnumType.STRING): Stores the enum as "CUSTOMER"/"ADMIN"/"SELLER"
 *       strings in the DB, NOT as ordinal numbers (0, 1, 2). NEVER use EnumType.ORDINAL
 *       because adding/reordering enum values changes the numeric mapping and corrupts data.</li>
 * </ul>
 *
 * @see com.smartshop.user.dto.UserDto
 * @see com.smartshop.user.mapper.UserMapper
 * @author SmartShop Team
 */
@Entity
@Table(
    name = "users",
    indexes = {
        // Index on email for fast lookup during login (the most common query)
        // Without this index, every login would do a full table scan
        @Index(name = "idx_users_email", columnList = "email"),
        // Index on username for profile lookups
        @Index(name = "idx_users_username", columnList = "username")
    }
)
// Connect Spring Data's auditing listener to auto-populate audit fields
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Primary key — auto-generated by the database using an identity sequence.
     * GenerationType.IDENTITY: PostgreSQL handles sequence generation natively.
     * Alternative: GenerationType.SEQUENCE with a named sequence (better performance
     * in batch inserts because Hibernate can pre-allocate sequence blocks).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique display name chosen by the user.
     * nullable=false: enforced at both JPA level and DB level (NOT NULL constraint).
     * The Flyway migration also adds NOT NULL and UNIQUE to this column.
     */
    @Column(name = "username", nullable = false, unique = true, length = 50)
    private String username;

    /**
     * User's email — also the login identifier.
     * Must be unique across the platform (enforced by DB unique constraint).
     */
    @Column(name = "email", nullable = false, unique = true, length = 100)
    private String email;

    /**
     * BCrypt-hashed password. NEVER store plain-text passwords.
     *
     * WHY BCrypt?
     * BCrypt is a password hashing function designed to be SLOW (deliberately):
     *   - It uses a "cost factor" (default 10-12) that makes it ~100ms per hash
     *   - Slowing down legitimate login by 100ms is acceptable
     *   - But it makes brute-force attacks 1000x harder than MD5/SHA
     *   - BCrypt automatically generates and embeds a random SALT per password
     *     (prevents rainbow table attacks)
     * Format: $2a$10$[22 chars salt][31 chars hash]
     * The `$10$` part is the cost factor — increase it when hardware gets faster.
     */
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    /** User's first name */
    @Column(name = "first_name", length = 50)
    private String firstName;

    /** User's last name */
    @Column(name = "last_name", length = 50)
    private String lastName;

    /**
     * User's role determines what they can access.
     * Stored as STRING (e.g., "CUSTOMER") not ordinal (0) to be robust against
     * future enum changes.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20)
    @Builder.Default
    private Role role = Role.CUSTOMER;

    /**
     * Whether this account is active and can log in.
     * Deactivated accounts can't log in but their data is retained (soft delete).
     * GDPR "right to erasure" would require a hard delete, but for most cases
     * deactivation is the safer approach.
     */
    @Column(name = "enabled", nullable = false)
    @Builder.Default
    private boolean enabled = true;

    // =======================================================================
    // JPA AUDITING FIELDS
    // Automatically populated by Spring Data JPA's AuditingEntityListener
    // when @EnableJpaAuditing is on the @SpringBootApplication class.
    // =======================================================================

    /**
     * Timestamp of when this user record was created.
     * @CreatedDate: set once on INSERT, never modified.
     * updatable=false enforces this at the DB level too.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Timestamp of the last modification to this record.
     * @LastModifiedDate: updated on every UPDATE automatically.
     */
    @LastModifiedDate
    @Column(name = "updated_at")
    private Instant updatedAt;

    /**
     * The username of who created this record.
     * "system" for registrations (no logged-in user), admin username for admin-created users.
     */
    @CreatedBy
    @Column(name = "created_by", updatable = false, length = 50)
    private String createdBy;

    /**
     * The username of who last modified this record.
     */
    @LastModifiedBy
    @Column(name = "updated_by", length = 50)
    private String updatedBy;
}
