package com.smartshop.user.dto;

/**
 * AuthResponse - Returned after a successful register/login.
 *
 * <h2>Purpose</h2>
 * Bundles the freshly minted JWT with a safe view of the user, so the client
 * gets everything it needs in one round-trip: the token to authenticate future
 * calls, plus who they are logged in as.
 *
 * <h2>Key Concepts</h2>
 * <ul>
 *   <li>{@code tokenType} is "Bearer" — the client sends
 *       {@code Authorization: Bearer <accessToken>} on subsequent requests.</li>
 *   <li>{@code expiresInMs} lets the client proactively refresh before expiry.</li>
 * </ul>
 *
 * <h2>How it fits in the system</h2>
 * Built by {@code UserServiceImpl} after credentials are verified and a token is
 * generated by {@code JwtService}.
 *
 * @param accessToken the signed JWT
 * @param tokenType   always "Bearer"
 * @param expiresInMs token lifetime in milliseconds
 * @param user        safe user view
 * @author SmartShop Team
 */
public record AuthResponse(
        String accessToken,
        String tokenType,
        long expiresInMs,
        UserDto user
) {
    /**
     * Convenience factory that fixes the token type to "Bearer".
     *
     * @param accessToken signed JWT
     * @param expiresInMs token lifetime in ms
     * @param user        safe user view
     * @return a populated {@code AuthResponse}
     */
    public static AuthResponse bearer(String accessToken, long expiresInMs, UserDto user) {
        return new AuthResponse(accessToken, "Bearer", expiresInMs, user);
    }
}
